server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
my:
  ages:
    int: 21
    str: 'test string'
spring:
  application:
    name: first-config-client
